language: java

jdk:
  - openjdk8

stages:
  - Test
  - VM

jobs:
  include:
    - stage : Test
      
      script:
        - mvn clean install

    - stage: VM
      if: type != pull_request AND (branch = master OR branch = development OR branch = returnFromUInew)
      language: java
      before_script:
      - if [ $TRAVIS_BRANCH == "development" ]; then
            export CONTAINER_TAG="0.0.3";
        elif [ $TRAVIS_BRANCH == "master" ]; then
            export CONTAINER_TAG=latest;
        elif [ $TRAVIS_BRANCH == "returnFromUInew" ]; then
            export CONTAINER_TAG=test;
        fi
      script:
        - docker login -u "$DOCKER_USERNAME_MVJ" -p "$DOCKER_PASSWORD_MVJ"
        - docker build -t mvjatos/seal-rm:${CONTAINER_TAG} .
        - docker push mvjatos/seal-rm:${CONTAINER_TAG}
